spring:
  application:
    name: dmeo-application-mongodb

  data:
    # MongoDB 配置项，对应 MongoProperties 类
    mongodb:
      host: 192.168.56.10
      port: 27017
      database: yourdatabase
      username: test01
      password: password01
      # 上述属性，也可以只配置 uri
